monitor = HDMI-A-1, 1920x1080@60, 0x0, 1

exec-once = emacs --daemon
exec-once = awww-daemon
exec-once = $HOME/scripts/cycle-walls.sh $HOME/.config/wallpaper/

input {
  sensitivity = -0.9
}

bind = $mainMod SUPER, e, exec, emacsclient -c
