# Rebind default preffix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split orientation
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# Set Zsh as the default shell for new windows/panes
set-option -g default-shell /bin/zsh

# --- Prefix Key (Default C-b) ---
# The default prefix key (Ctrl+b) is kept.
# You can reload the config file with the default prefix + r (Ctrl+b, then r)
bind r source-file ~/.tmux.conf \; display "Tmux Config Reloaded!"

# --- Key Bindings & Mode (Vim) ---

# Enable Vi/Vim keybindings in copy/selection mode
set-window-option -g mode-keys vi

# Change the default escape time to reduce delay when pressing Esc
set-option -sg escape-time 10

# Use 'v' to begin selection (like visual mode in Vim)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Use 'y' to copy to the system clipboard
# Requires 'xclip' or 'xsel' on Linux, or 'pbcopy' on macOS
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
# If you are on macOS, you would use this instead:
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# Enable mouse support
set-option -g mouse on

# Allow passthrough of Kitty graphics protocol (needed for image.nvim / snacks)
set -g allow-passthrough on
set -g default-terminal "xterm-kitty"

set -g extended-keys on
