# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$ 
windowrule = size 307 340, match:title ^(HyprEmoji)$
