ui {
  window_size = 600 400
  color.background = 0xff24273a
    color.border = 0xff8aadf4
    color.text = 0xffcad3f5
    color.selected = 0xffc6a0f6

    # Styling
    border_size = 2
    rounding = 12
}
